### ISSUE TITLE
package import and location Clarity and Control

### ISSUE THREAD

**Issue by salvor7** [quiltdata/quilt-compiler#163]
From the way I understood quilt to work, I expected to be able to call 
"quilt build user/package folder"
from anywhere, and I would end up with an importable data package right away. However, this is working in a very sporadic way for me which I'll try to detail. These all seem to me to be related problems, but I'll be happy to break it up into multiple issues if that is easier to manage. 

**First**, where ever I call the build command is where the quilt package is built. As the default I find this quite weird, as I quickly ended up with data packages all over the place. My expectation was that the packages would be managed in a way similar to python packages: some central place on disk.

**Second**, that default is also problematic as packages that I have built are not available for import from other locations (with one exception in 3rd) unless I set my current working directory manually. To access the standard library or any installed module, it doesn't matter what my current working directory is, and that is what I expected from the quilt packages. But so far, if I have the quilt packages in anywhere but one spot, the working directory of my code has to be the same as the quilt package folder or else the import fails. This breaks the promise of having data importable like modules. 

**Third** On my macbook, I have found that all the packages in
"Users/username/quilt_packages"
are available for import regardless of my working directory. For the most part, this has served my purposes. However, I now have a need to have some of the quilt packages in another folder, so I am back to manipulating the working directory.

**Fourth** On my windows 10 laptop, there is no folder at all that allows a package import from anywhere, so I always have to manipulate the working directory in Windows.

**Fifth** I have also not found a way to use packages in PyCharm yet. Adding the quilt_packages folder as a source folder does not make the data packages visible to PyCharm.

**Comment by akarve** [comment]
Good write-up. Thanks. I think I understand the issues and can propose relevant fixes. In some cases we'll break these out into separate issues.

First let me clarify is how `import`s are resolved. The algorithm is for `quilt` to look in the current working directory, and then walk up the directory tree checking all ancestors of the current working directory. The first match in the ancestry is what's imported. If you happen to be in a peer or parent directory to a `quilt_packages` dir that contains the package that you want, and their is no such match in the ancestry of the working directory, `import` will fail. I think this is the right behavior for `import` (modeled on `npm`, allows for selective override via child directories, etc.).

The thing that I think we are doing wrong, and that is causing the confusion, is that `quilt build` defaults to `.`. I can see a good argument for `build` defaulting to `~` which would give the behavior that you desire.

Issue *four* sounds like a Windows specific bug and we'll need to investigate. Do you experience this bug even if you install `quilt_packages` in HOME and then work underneath home? I'm not yet clear how no folder allows an import but changing the working directory helps. If this is indeed a bug let's break this out into a separate issue.

Issue *five* sounds related to how PyCharm sets the current working directory? Smells vaguely like the [Jupyter issue](https://docs.quiltdata.com/troubleshooting.html). Needs investigation. Also a good candidate for a separate Issue.

**Comment by salvor7** [comment]
I didn't understand npm importing prior to now, so the searching ancestors idea wasn't in my thought process. I'll double check that the windows problems and MacOS home folder thing don't just result from ancestor searching. This may provide the ideas I need to wrangle PyCharm also. The main upshot for me here is the need for the import story to be described somewhere in both high level and fine detail regardless of how transparent you are able to make it. 

The idea of defaulting to ~ instead of . makes sense to me when coupled with the ability to change that location as a CLI option. 

A final thought. I was attracted to quilt for the ability to decouple data from data use. But the ancestor relation for importing implicitly insists that there be a folder relationship between the data and the use. This again breaks the promise of importing data like python modules, as python modules do not need to be folder related to where they are used. The PYTHONPATH variable accomplishes this for modules, so perhaps a transparently managed QUILTPATH could accomplish it for data packages.

**Comment by akarve** [comment]
I think we can both default to `HOME` and make `QUILTPATH` configurable. Filed as #2. Let us know how the remaining items resolve (or not) so we can make issue for them..

**Comment by salvor7** [comment]
The windows and MacOS differences had entirely to do with the relative location of my projects folder. On my MacOS, my projects folder and quilt_packages folder were both in ~, so all my imports worked. On Win10, my projects folder was not, so no imports worked. Understanding how quilt finds package imports via and folder ancestry search clarified greatly. 

For Pycharm, I am not sure what project setting I could use to set up quilt packages. The imports work if the quilt_packages folder is an ancestor of the folder where I'm running the code. But setting source folders doesn't seem to work to allow the import if the quilt_packages folder isn't in an ancestor folder.  Also, the code high lighting marks the quilt package import as an error regardless of whether the import will work or not.

**Comment by akarve** [comment]
Will handle on #164
